export const PERMISSIONS = {
  DASHBOARD_VIEW: "dashboard:view",
  ROOM_MAP_VIEW: "room_map:view",
  BOOKING_VIEW: "booking:view",
  BOOKING_CREATE: "booking:create",
  BOOKING_EDIT: "booking:edit",
  BOOKING_CANCEL: "booking:cancel",
  GUEST_VIEW: "guest:view",
  GUEST_EDIT: "guest:edit",
  HOUSEKEEPING_VIEW: "housekeeping:view",
  HOUSEKEEPING_MANAGE: "housekeeping:manage",
  BILLING_VIEW: "billing:view",
  BILLING_MANAGE: "billing:manage",
  MASTER_DATA_VIEW: "master_data:view",
  MASTER_DATA_MANAGE: "master_data:manage",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<string, string[]> = {
  ADMIN: Object.values(PERMISSIONS),
  MANAGER: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.ROOM_MAP_VIEW,
    PERMISSIONS.BOOKING_VIEW,
    PERMISSIONS.BOOKING_CREATE,
    PERMISSIONS.BOOKING_EDIT,
    PERMISSIONS.BOOKING_CANCEL,
    PERMISSIONS.GUEST_VIEW,
    PERMISSIONS.GUEST_EDIT,
    PERMISSIONS.HOUSEKEEPING_VIEW,
    PERMISSIONS.HOUSEKEEPING_MANAGE,
    PERMISSIONS.BILLING_VIEW,
    PERMISSIONS.BILLING_MANAGE,
    PERMISSIONS.MASTER_DATA_VIEW,
    PERMISSIONS.MASTER_DATA_MANAGE,
  ],
  RECEPTIONIST: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.ROOM_MAP_VIEW,
    PERMISSIONS.BOOKING_VIEW,
    PERMISSIONS.BOOKING_CREATE,
    PERMISSIONS.BOOKING_EDIT,
    PERMISSIONS.GUEST_VIEW,
    PERMISSIONS.GUEST_EDIT,
    PERMISSIONS.BILLING_VIEW,
  ],
  HOUSEKEEPING: [
    PERMISSIONS.ROOM_MAP_VIEW,
    PERMISSIONS.HOUSEKEEPING_VIEW,
    PERMISSIONS.HOUSEKEEPING_MANAGE,
  ],
};
