export const ROOM_STATUS_CODES = {
  AVAILABLE: "AVAILABLE",
  OCCUPIED: "OCCUPIED",
  RESERVED: "RESERVED",
  CLEANING: "CLEANING",
  MAINTENANCE: "MAINTENANCE",
  OUT_OF_SERVICE: "OUT_OF_SERVICE",
} as const;

export type RoomStatusCode = (typeof ROOM_STATUS_CODES)[keyof typeof ROOM_STATUS_CODES];
