export const ROUTES = {
  DASHBOARD: "/dashboard",
  HISTORY: "/history",
  ROOM_MAP: "/room-map",
  ROOMS: "/rooms",
  ROOM_HISTORY: (id: string) => `/rooms/${id}/history`,
  RESERVATIONS: "/reservations",
  GUESTS: "/guests",
  HOUSEKEEPING: "/housekeeping",
  BILLING: "/billing",
  STAFF: "/staff",
  ACCOUNTS: "/accounts",
  SETTINGS: "/settings",
  INVENTORY: "/inventory",
  EXPENSES: "/expenses",
  FINANCE: "/finance",
  LONG_TERM: {
    LEASES: "/long-term/leases",
    BILLS: "/long-term/bills",
    METER_READINGS: "/long-term/meter-readings",
    FEE_ITEMS: "/long-term/fee-items",
    RATE_PLANS: "/long-term/rate-plans",
  },
  MASTER: {
    FLOORS: "/master-data/floors",
    ROOM_TYPES: "/master-data/room-types",
    ROOM_STATUSES: "/master-data/room-statuses",
    BOOKING_STATUSES: "/master-data/booking-statuses",
    PAYMENT_METHODS: "/master-data/payment-methods",
    SERVICE_ITEMS: "/master-data/service-items",
    GUEST_TYPES: "/master-data/guest-types",
    AMENITIES: "/master-data/amenities",
    ROOM_TYPE_PRICING: "/master-data/room-type-pricing",
    PRODUCT_CATEGORIES: "/master-data/product-categories",
    PRODUCTS: "/master-data/products",
    EXPENSE_CATEGORIES: "/master-data/expense-categories",
    EXPENSE_ITEMS: "/master-data/expense-items",
  },
} as const;
