export const ROUTES = {
  DASHBOARD: "/dashboard",
  HISTORY: "/history",
  ROOM_MAP: "/room-map",
  ROOMS: "/rooms",
  ROOM_HISTORY: (id: string) => `/rooms/${id}/history`,
  RESERVATIONS: "/reservations",
  GUESTS: "/guests",
  HOUSEKEEPING: "/housekeeping",
  BILLING: "/billing",
  STAFF: "/staff",
  ACCOUNTS: "/accounts",
  SETTINGS: "/settings",
  MASTER: {
    FLOORS: "/master-data/floors",
    ROOM_TYPES: "/master-data/room-types",
    ROOM_STATUSES: "/master-data/room-statuses",
    BOOKING_STATUSES: "/master-data/booking-statuses",
    PAYMENT_METHODS: "/master-data/payment-methods",
    SERVICE_ITEMS: "/master-data/service-items",
    GUEST_TYPES: "/master-data/guest-types",
    AMENITIES: "/master-data/amenities",
    ROOM_TYPE_PRICING: "/master-data/room-type-pricing",
  },
} as const;
